http: {
    upstream myapp {
        server ip_address_of_docker_container1:port1;       #( ports are the ports on which your docker containers are running in our case it's 8081, 8082, 8083)
        server ip_address_of_docker_container2:port2;
        server ip_address_of_docker_container3:port3;
    }

    server {
        listen 80;
        server_name _;
        

        location / {
            proxy_pass http://myapp;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}